
trigger:
- main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

- task: Docker@2
  inputs:
    containerRegistry: 'BinduACR1'
    repository: 'BinduACR1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'BinduACR1'
    repository: 'BinduACR1'
    command: 'buildAndPush'
    Dockerfile: '**/sqlimage/Dockerfile'


   
    
  
    