version: "3.8"

services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
    - 5000:5000
    networks:
      - bindu-network

  mysql:
    build:
      context: ./sqlimage
      dockerfile: Dockerfile
    container_name: mysql
    volumes:
      - bindu:/var/lib/mysql
    networks:
      - bindu-network

networks:
  bindu-network:
    driver: bridge

volumes:
  bindu:

      
