name: Myfirstworkflow
on: push
jobs:
  unit-testing:
    name: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: 424bindu
          password: Bindu@9003109773

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: 424bindu/may23:latest
      
   
