name: Myfirstworkflow
on: push
jobs:
  unit-testing:
    name: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: list files
        run: ls -l
